{{- if .Values.authBridge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-nova-operator-kog.authBridgeName" . }}
  labels:
    {{- include "openstack-nova-operator-kog.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-bridge
spec:
  type: {{ .Values.authBridge.service.type }}
  ports:
    - port: {{ .Values.authBridge.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openstack-nova-operator-kog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth-bridge
{{- end }}
