{{- if .Values.authBridge.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-nova-operator-kog.authBridgeName" . }}
  labels:
    {{- include "openstack-nova-operator-kog.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-bridge
spec:
  replicas: {{ .Values.authBridge.replicaCount }}
  selector:
    matchLabels:
      {{- include "openstack-nova-operator-kog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth-bridge
  template:
    metadata:
      {{- with .Values.authBridge.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openstack-nova-operator-kog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: auth-bridge
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.authBridge.image.repository }}:{{ .Values.authBridge.image.tag }}"
          imagePullPolicy: {{ .Values.authBridge.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.authBridge.resources | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: conf
          configMap:
            name: {{ include "openstack-nova-operator-kog.authBridgeName" . }}
            items:
              - key: default.conf
                path: default.conf
      {{- with .Values.authBridge.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authBridge.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authBridge.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
